nf31
blues/app-accelerators pull request #105
Opened 2023-03-11 02:33 UTC by m-mcgowan

2023-03-11 02:34 UTC, m-mcgowan commented
![](https://github.trello.services/images/mini-trello-icon.png) [NF31 - Sparrow Firmware and writeup](https://trello.com/c/tLoZp3fZ/178-nf31-sparrow-firmware-and-writeup)

2023-03-11 08:09 UTC, haydenroche5 requested changes
Looks good overall. There are a few files missing newlines at the end, btw.

2023-03-11 08:09 UTC, haydenroche5 commented on 31-temperature-and-smoke-detector/firmware/sparrow-application/mq2/mq2.c
> +    (void)appID;
`appId` is used, so we can remove this, I think.

2023-03-13 17:04 UTC, haydenroche5 approved these changes

2023-03-13 17:05 UTC, merged

2023-03-13 21:03 UTC, m-mcgowan commented
![](https://github.trello.services/images/mini-trello-icon.png) [NF31 - Temperature and Smoke Detector](https://trello.com/c/sSjzwnEp/176-nf31-temperature-and-smoke-detector)