chore: refactoring project docs to have a root README
blues/app-accelerators pull request #133
Opened 2023-05-26 19:33 UTC by tjvantoll

# Problem Context

## Changes

## Screenshot (if applicable)

## Testing

Unit / integration / e2e tests?
Steps to test manually?
Any other sorts of testing notes to include?

## Any other related PRs

## Ticket(s)

2023-05-31 22:02 UTC, haydenroche5 requested changes

2023-05-31 22:02 UTC, haydenroche5 commented on 18-temperature-and-humidity-monitor/firmware/zephyr/README.md
> +And refer to this project's [Operation documentation](../../README.md#operation) for details on the data your device is now sending.
I think we can drop the "And" and just start with "Refer".

2023-06-01 12:38 UTC, tjvantoll commented
@haydenroche5 Good catches. Pushed updates for all your suggestions.

2023-06-01 16:46 UTC, haydenroche5 approved these changes

2023-06-01 17:44 UTC, merged