Add firmware for NF10.
blues/app-accelerators pull request #63
Opened 2022-12-15 22:09 UTC by haydenroche5

The firmware source code for NF9 and 10 is identical. NF10's main.cpp is just a symbolic link to NF9's main.cpp. Valve support is compiled in by defining the macro USE_VALVE to 1. It's compiled out by setting USE_VALVE to 0. The platform.ini build_flags set this macro accordingly for each project.

2023-01-06 17:35 UTC, paigen11 commented
@haydenroche5 would you mind resolving the conflicts in your branch and merging to the `nf10` branch for final review before it goes public?

2023-01-09 19:40 UTC, m-mcgowan requested changes
LGTM - just the ProductUID thing.

2023-01-09 19:40 UTC, m-mcgowan commented on valve-monitor/firmware/src/main.cpp
> +#define PRODUCT_UID "com.blues.hroche:quickstart"
Can we leave this undefined by default, like this: https://github.com/blues/app-accelerators/blob/main/08-power-monitoring-and-control/firmware/src/app.h#L12

2023-01-09 19:40 UTC, m-mcgowan commented on valve-monitor/firmware/src/main.cpp
> +#define PRODUCT_UID "com.blues.hroche:quickstart"
Also please note that we have a short link, just in case the docs layout changes.

2023-01-10 17:47 UTC, m-mcgowan approved these changes

2023-01-10 18:22 UTC, merged